### ISSUE TITLE
Add header and footer for context and other links

### ISSUE THREAD

**Issue by whykatherine** [creativecodecollective/creativecodecollective.github.io#10]
Possible suggestions for header (whether a horizontal bar or a whole section):
- Title (Creative Code Collective)
- About
- How to use site/resource hub

Possible suggestions for footer:
- (Link to?) list of contributors! Anyone who works on code, design, adding/editing resources, documentation, or other things
- Contact information (email, location, hours)

Other thoughts:
- Partners/peer organisations?

**Comment by sarahciston** [comment]
Yes, love all this! Would help to decide on a logo or style guide, or at least a couple colors/fonts, a look that we'd like to start with. I'd vote for a mix of feeling fun, approachable and clean, minimal, code-y.

**Comment by sarahciston** [comment]
I'm thinking we can add the List of Contributors to the About Page? Working on a starter header and will add dummy links for all the rest.

**Comment by whykatherine** [comment]
got it! https://github.com/creativecodecollective/creativecodecollective.github.io/commit/a5aac784995c048777fd737409745470c1a9242f
