### ISSUE TITLE
Sarah can't install Jekyll and feels annoyed/dumb lol

### ISSUE THREAD

**Issue by sarahciston** [creativecodecollective/creativecodecollective.github.io#25]
`$ gem install --user-install bundler jekyll
WARNING:  You don't have /Users/sarahciston/.gem/ruby/2.3.0/bin in your PATH,
          gem executables will not run.
Successfully installed bundler-2.1.4`
------
`$sudo gem install -n /usr/local/bin/ jekyll
ERROR:  Error installing jekyll:
ERROR: Failed to build gem native extension.
    current directory: /Users/sarahciston/.gem/ruby/2.3.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20200304-34963-141wkap.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h
extconf failed, exit code 1`

**Comment by sarahciston** [comment]
This was the dumbest worst thing ever.

**Comment by gurumatcha** [comment]
We followed this https://github.com/ffi/ffi/issues/653#issuecomment-518062877
But what really helped was fixing the PATH issues.
We put the ruby path at the top of the `.bash_profile` before miniconda's stuff
