### ISSUE TITLE
update creativecodecollective.com redirect to this github page, as our public beta reveal with new semester? 

### ISSUE THREAD

**Issue by sarahciston** [creativecodecollective/creativecodecollective.github.io#30]
I'd say let's go for it, if we can just add in the contact info for me (ciston@usc.edu) and the Wednesdays 4-6pm meeting time, plus any other design stuff (or not), I am happy to change the url from the cats home page to this living growing github homepage instead! LMK?

**Comment by whykatherine** [comment]
done!
