### ISSUE TITLE
Resources not showing up on homepage

### ISSUE THREAD

**Issue by whykatherine** [creativecodecollective/creativecodecollective.github.io#7]
Check Jekyll documentation to figure out how to automatically display all resources as items on the homepage.

**Comment by gurumatcha** [comment]
I had tried putting the resources under a collection in `_config.yml` but didn't seem to work

**Comment by whykatherine** [comment]
Hey @gurumatcha! I just fiddled with it locally and might have gotten it to work. Following [Jekyll documentation](https://jekyllrb.com/docs/collections/), I just added
```
collections
  - resources
```
to _config.yml like you did. Then I renamed the resources folder to _resources (you were right with the cloning, we can delete the old one without the underscore I think), and then I changed in index.html:
* `{% for resource in collections.all %}` becomes `{% for resource in site.resources %}`
* `{% resource.data.title %}` becomes `{% resource.title %}` and same for the other values
Does that work for you?

**Comment by gurumatcha** [comment]
I don't have the ability to jekyll locally rn, so push and see?

**Comment by gurumatcha** [comment]
yoooo it workssssss
<3 <3 <3 <#
i'll keep pluggin away at gettin those thumbnails to work

**Comment by gurumatcha** [comment]
works! we must alter the css

**Comment by whykatherine** [comment]
css has been somewhat altered
